nombre = input ("Cual es tu nombre?\n")
print ("Vale", nombre)
raza = input ("Y cual es tu raza?\n")
print ("Okay", raza)
clase = input ("Cual es tu clase?\n")
print ("Entonces\n", clase)
nivel = input ("De que nivel eres?\n")
vida = input ("Cuanta vida tienes?\n")
Print = ("Wow ", vida)

print("===Hoja de personaje===")
print("Nombre:",nombre)
print("Raza:",raza)
print("clase:",clase)
print("nivel:",nivel)
print("vida:",vida)
